Key Deliverables 
- EntityExtractor class with regex patterns for numeric entities ✅
- Amenity detection using Week 1 taxonomy ✅
- Labeled dataset: 200-300 remarks with entity spans 
- Evaluation script calculating precision/recall/F1 
- Target: 85%+ F1 score on test set 
- Error analysis identifying top failure patterns

Objective: Build a program that reads a real estate listing description/remarks and pull out important information into a structured format

In [515]:
import re 
from collections import Counter
import json
import pandas as pd
import sys
sys.path.append("../scripts")

In [516]:
from w2_text_cleaning import TextCleaner

In [517]:
with open("../data/processed/taxonomy.json", "r") as f:
    taxonomy = json.load(f)
print("Total terms:", len(taxonomy["terms"]))
print(taxonomy["categories"])
print()
term_counts = Counter(term["category"] for term in taxonomy["terms"])

print("Term Counts per Category")
for category in taxonomy["categories"]:
    count = term_counts.get(category, 0)
    print(f"{category}: {count} terms")

Total terms: 200
['kitchen', 'flooring', 'outdoor', 'parking', 'housing_layout', 'housing_features', 'location', 'community_amenities']

Term Counts per Category
kitchen: 22 terms
flooring: 13 terms
outdoor: 31 terms
parking: 20 terms
housing_layout: 43 terms
housing_features: 41 terms
location: 28 terms
community_amenities: 2 terms

In [518]:
print(taxonomy['terms'])

[{'id': 1, 'term': 'primary suite', 'category': 'housing_layout', 'frequency': 336}, {'id': 2, 'term': 'natural light', 'category': 'housing_features', 'frequency': 294}, {'id': 3, 'term': 'living room', 'category': 'housing_layout', 'frequency': 283}, {'id': 4, 'term': 'living space', 'category': 'outdoor', 'frequency': 263}, {'id': 5, 'term': 'floor plan', 'category': 'flooring', 'frequency': 261}, {'id': 6, 'term': 'stainless steel', 'category': 'kitchen', 'frequency': 193}, {'id': 7, 'term': 'everyday living', 'category': 'parking', 'frequency': 186}, {'id': 8, 'term': 'stainless steel appliances', 'category': 'kitchen', 'frequency': 172}, {'id': 9, 'term': 'shopping dining', 'category': 'location', 'frequency': 171}, {'id': 10, 'term': 'located near', 'category': 'location', 'frequency': 159}, {'id': 11, 'term': 'conveniently located', 'category': 'location', 'frequency': 158}, {'id': 12, 'term': 'home office', 'category': 'housing_layout', 'frequency': 143}, {'id': 13, 'term': 'pool spa', 'category': 'outdoor', 'frequency': 143}, {'id': 14, 'term': 'easy access', 'category': 'housing_features', 'frequency': 139}, {'id': 15, 'term': 'family room', 'category': 'housing_layout', 'frequency': 134}, {'id': 16, 'term': 'bedrooms bathrooms', 'category': 'housing_layout', 'frequency': 131}, {'id': 17, 'term': 'laundry room', 'category': 'housing_features', 'frequency': 130}, {'id': 18, 'term': 'recessed lighting', 'category': 'housing_features', 'frequency': 119}, {'id': 19, 'term': 'quartz countertops', 'category': 'kitchen', 'frequency': 117}, {'id': 20, 'term': 'living spaces', 'category': 'outdoor', 'frequency': 113}, {'id': 21, 'term': 'granite countertops', 'category': 'kitchen', 'frequency': 103}, {'id': 22, 'term': 'conveniently located near', 'category': 'location', 'frequency': 103}, {'id': 23, 'term': 'everyday living entertaining', 'category': 'parking', 'frequency': 96}, {'id': 24, 'term': 'spacious living', 'category': 'outdoor', 'frequency': 95}, {'id': 25, 'term': 'dining room', 'category': 'housing_layout', 'frequency': 92}, {'id': 26, 'term': 'main level', 'category': 'parking', 'frequency': 89}, {'id': 27, 'term': 'ideally located', 'category': 'location', 'frequency': 88}, {'id': 28, 'term': 'attached garage', 'category': 'parking', 'frequency': 85}, {'id': 29, 'term': 'open floor', 'category': 'flooring', 'frequency': 85}, {'id': 30, 'term': 'vaulted ceilings', 'category': 'housing_features', 'frequency': 84}, {'id': 31, 'term': 'primary bedroom', 'category': 'housing_layout', 'frequency': 84}, {'id': 32, 'term': 'kitchen features', 'category': 'kitchen', 'frequency': 83}, {'id': 33, 'term': 'abundant natural light', 'category': 'housing_features', 'frequency': 83}, {'id': 34, 'term': 'open floor plan', 'category': 'flooring', 'frequency': 83}, {'id': 35, 'term': 'spacious primary', 'category': 'outdoor', 'frequency': 82}, {'id': 36, 'term': 'golf course', 'category': 'location', 'frequency': 79}, {'id': 37, 'term': 'suite offers', 'category': 'housing_layout', 'frequency': 78}, {'id': 38, 'term': 'mountain views', 'category': 'location', 'frequency': 78}, {'id': 39, 'term': 'private balcony', 'category': 'outdoor', 'frequency': 75}, {'id': 40, 'term': 'full bathroom', 'category': 'housing_layout', 'frequency': 74}, {'id': 41, 'term': 'flooring throughout', 'category': 'flooring', 'frequency': 73}, {'id': 42, 'term': 'tile flooring', 'category': 'flooring', 'frequency': 72}, {'id': 43, 'term': 'gated community', 'category': 'community_amenities', 'frequency': 72}, {'id': 44, 'term': 'covered patio', 'category': 'outdoor', 'frequency': 70}, {'id': 45, 'term': 'primary suite offers', 'category': 'housing_layout', 'frequency': 69}, {'id': 46, 'term': 'updated kitchen', 'category': 'kitchen', 'frequency': 68}, {'id': 47, 'term': 'direct access', 'category': 'housing_features', 'frequency': 68}, {'id': 48, 'term': 'additional bedrooms', 'category': 'housing_layout', 'frequency': 65}, {'id': 49, 'term': 'spacious primary suite', 'category': 'outdoor', 'frequency': 65}, {'id': 50, 'term': 'car garage', 'category': 'parking', 'frequency': 63}, {'id': 51, 'term': 'fitness center', 'category': 'housing_features', 'frequency': 62}, {'id': 52, 'term': 'center island', 'category': 'kitchen', 'frequency': 61}, {'id': 53, 'term': 'flows seamlessly', 'category': 'housing_features', 'frequency': 60}, {'id': 54, 'term': 'home located', 'category': 'location', 'frequency': 59}, {'id': 55, 'term': 'full bath', 'category': 'housing_layout', 'frequency': 58}, {'id': 56, 'term': 'chef kitchen', 'category': 'kitchen', 'frequency': 58}, {'id': 57, 'term': 'hardwood floors', 'category': 'flooring', 'frequency': 58}, {'id': 58, 'term': 'convenient access', 'category': 'housing_features', 'frequency': 58}, {'id': 59, 'term': 'bedroom full', 'category': 'housing_layout', 'frequency': 57}, {'id': 60, 'term': 'outdoor space', 'category': 'outdoor', 'frequency': 57}, {'id': 61, 'term': 'bedrooms full', 'category': 'housing_layout', 'frequency': 57}, {'id': 62, 'term': 'freeway access', 'category': 'housing_features', 'frequency': 55}, {'id': 63, 'term': 'brand new', 'category': 'housing_layout', 'frequency': 54}, {'id': 64, 'term': 'panoramic views', 'category': 'location', 'frequency': 53}, {'id': 65, 'term': 'sliding glass', 'category': 'housing_features', 'frequency': 52}, {'id': 66, 'term': 'remodeled kitchen', 'category': 'kitchen', 'frequency': 52}, {'id': 67, 'term': 'cozy fireplace', 'category': 'housing_features', 'frequency': 51}, {'id': 68, 'term': 'prime location', 'category': 'location', 'frequency': 50}, {'id': 69, 'term': 'private backyard', 'category': 'outdoor', 'frequency': 50}, {'id': 70, 'term': 'detached garage', 'category': 'parking', 'frequency': 48}, {'id': 71, 'term': 'peace mind', 'category': 'housing_features', 'frequency': 48}, {'id': 72, 'term': 'seamless flow', 'category': 'housing_features', 'frequency': 48}, {'id': 73, 'term': 'solar panels', 'category': 'housing_features', 'frequency': 48}, {'id': 74, 'term': 'gourmet kitchen', 'category': 'kitchen', 'frequency': 47}, {'id': 75, 'term': 'bedroom bath', 'category': 'housing_layout', 'frequency': 47}, {'id': 76, 'term': 'filled natural light', 'category': 'housing_features', 'frequency': 47}, {'id': 77, 'term': 'located minutes', 'category': 'location', 'frequency': 46}, {'id': 78, 'term': 'near shopping', 'category': 'location', 'frequency': 46}, {'id': 79, 'term': 'countertops stainless', 'category': 'kitchen', 'frequency': 46}, {'id': 80, 'term': 'features spacious', 'category': 'outdoor', 'frequency': 45}, {'id': 81, 'term': 'spacious living room', 'category': 'outdoor', 'frequency': 45}, {'id': 82, 'term': 'located within', 'category': 'location', 'frequency': 44}, {'id': 83, 'term': 'dining shopping', 'category': 'location', 'frequency': 44}, {'id': 84, 'term': 'tennis courts', 'category': 'community_amenities', 'frequency': 44}, {'id': 85, 'term': 'countertops stainless steel', 'category': 'kitchen', 'frequency': 44}, {'id': 86, 'term': 'high ceilings', 'category': 'housing_features', 'frequency': 43}, {'id': 87, 'term': 'sparkling pool', 'category': 'outdoor', 'frequency': 43}, {'id': 88, 'term': 'spacious bedrooms', 'category': 'outdoor', 'frequency': 43}, {'id': 89, 'term': 'formal dining room', 'category': 'housing_layout', 'frequency': 43}, {'id': 90, 'term': 'private patio', 'category': 'outdoor', 'frequency': 42}, {'id': 91, 'term': 'ample space', 'category': 'outdoor', 'frequency': 42}, {'id': 92, 'term': 'added privacy', 'category': 'housing_features', 'frequency': 42}, {'id': 93, 'term': 'features bedrooms', 'category': 'housing_layout', 'frequency': 41}, {'id': 94, 'term': 'wood flooring', 'category': 'flooring', 'frequency': 41}, {'id': 95, 'term': 'laminate flooring', 'category': 'flooring', 'frequency': 41}, {'id': 96, 'term': 'beautifully remodeled', 'category': 'housing_features', 'frequency': 40}, {'id': 97, 'term': 'glass doors', 'category': 'housing_features', 'frequency': 40}, {'id': 98, 'term': 'tankless water', 'category': 'housing_features', 'frequency': 40}, {'id': 99, 'term': 'secondary bedrooms', 'category': 'housing_layout', 'frequency': 40}, {'id': 100, 'term': 'schools shopping', 'category': 'location', 'frequency': 40}, {'id': 101, 'term': 'located near shopping', 'category': 'location', 'frequency': 40}, {'id': 102, 'term': 'bright open', 'category': 'housing_layout', 'frequency': 39}, {'id': 103, 'term': 'dual sinks', 'category': 'kitchen', 'frequency': 39}, {'id': 104, 'term': 'bedroom bathroom', 'category': 'housing_layout', 'frequency': 38}, {'id': 105, 'term': 'counter space', 'category': 'outdoor', 'frequency': 38}, {'id': 106, 'term': 'breakfast bar', 'category': 'kitchen', 'frequency': 38}, {'id': 107, 'term': 'room fireplace', 'category': 'housing_features', 'frequency': 38}, {'id': 108, 'term': 'ideally located near', 'category': 'location', 'frequency': 38}, {'id': 109, 'term': 'tankless water heater', 'category': 'housing_features', 'frequency': 38}, {'id': 110, 'term': 'two bedrooms', 'category': 'housing_layout', 'frequency': 37}, {'id': 111, 'term': 'offers bedrooms', 'category': 'housing_layout', 'frequency': 37}, {'id': 112, 'term': 'enjoy access', 'category': 'housing_features', 'frequency': 37}, {'id': 113, 'term': 'community pool', 'category': 'outdoor', 'frequency': 37}, {'id': 114, 'term': 'parking space', 'category': 'outdoor', 'frequency': 37}, {'id': 115, 'term': 'fruit trees', 'category': 'outdoor', 'frequency': 36}, {'id': 116, 'term': 'three bedrooms', 'category': 'housing_layout', 'frequency': 36}, {'id': 117, 'term': 'guests home office', 'category': 'housing_layout', 'frequency': 36}, {'id': 118, 'term': 'full bathrooms', 'category': 'housing_layout', 'frequency': 35}, {'id': 119, 'term': 'mature landscaping', 'category': 'outdoor', 'frequency': 35}, {'id': 120, 'term': 'sized bedrooms', 'category': 'housing_layout', 'frequency': 35}, {'id': 121, 'term': 'plank flooring', 'category': 'flooring', 'frequency': 35}, {'id': 122, 'term': 'located highly', 'category': 'location', 'frequency': 35}, {'id': 123, 'term': 'hardwood flooring', 'category': 'flooring', 'frequency': 34}, {'id': 124, 'term': 'designed everyday', 'category': 'parking', 'frequency': 34}, {'id': 125, 'term': 'comfort privacy', 'category': 'housing_features', 'frequency': 34}, {'id': 126, 'term': 'two additional bedrooms', 'category': 'housing_layout', 'frequency': 34}, {'id': 127, 'term': 'indoor laundry', 'category': 'housing_features', 'frequency': 33}, {'id': 128, 'term': 'everyday convenience', 'category': 'parking', 'frequency': 33}, {'id': 129, 'term': 'effortless entertaining', 'category': 'housing_features', 'frequency': 33}, {'id': 130, 'term': 'featuring bedrooms', 'category': 'housing_layout', 'frequency': 32}, {'id': 131, 'term': 'miss opportunity', 'category': 'housing_features', 'frequency': 31}, {'id': 132, 'term': 'fire pit', 'category': 'outdoor', 'frequency': 31}, {'id': 133, 'term': 'parks shopping', 'category': 'location', 'frequency': 31}, {'id': 134, 'term': 'ocean views', 'category': 'location', 'frequency': 31}, {'id': 135, 'term': 'bath home', 'category': 'housing_layout', 'frequency': 31}, {'id': 136, 'term': 'parking spaces', 'category': 'outdoor', 'frequency': 30}, {'id': 137, 'term': 'second bedroom', 'category': 'housing_layout', 'frequency': 30}, {'id': 138, 'term': 'room kitchen', 'category': 'kitchen', 'frequency': 30}, {'id': 139, 'term': 'ev charging', 'category': 'parking', 'frequency': 30}, {'id': 140, 'term': 'endless possibilities', 'category': 'housing_features', 'frequency': 30}, {'id': 141, 'term': 'shopping centers', 'category': 'location', 'frequency': 30}, {'id': 142, 'term': 'new roof', 'category': 'housing_features', 'frequency': 30}, {'id': 143, 'term': 'comfortable living space', 'category': 'outdoor', 'frequency': 30}, {'id': 144, 'term': 'large center island', 'category': 'kitchen', 'frequency': 30}, {'id': 145, 'term': 'shopping restaurants', 'category': 'location', 'frequency': 29}, {'id': 146, 'term': 'bedrooms baths', 'category': 'housing_layout', 'frequency': 29}, {'id': 147, 'term': 'outdoor kitchen', 'category': 'kitchen', 'frequency': 29}, {'id': 148, 'term': 'space home', 'category': 'outdoor', 'frequency': 29}, {'id': 149, 'term': 'upper level', 'category': 'parking', 'frequency': 29}, {'id': 150, 'term': 'patio perfect', 'category': 'outdoor', 'frequency': 29}, {'id': 151, 'term': 'spacious home', 'category': 'outdoor', 'frequency': 29}, {'id': 152, 'term': 'feet living space', 'category': 'outdoor', 'frequency': 29}, {'id': 153, 'term': 'kitchen showcases', 'category': 'kitchen', 'frequency': 28}, {'id': 154, 'term': 'laundry area', 'category': 'housing_features', 'frequency': 28}, {'id': 155, 'term': 'gas fireplace', 'category': 'housing_features', 'frequency': 28}, {'id': 156, 'term': 'bedroom full bathroom', 'category': 'housing_layout', 'frequency': 28}, {'id': 157, 'term': 'near shopping dining', 'category': 'location', 'frequency': 28}, {'id': 158, 'term': 'generously sized bedrooms', 'category': 'housing_layout', 'frequency': 28}, {'id': 159, 'term': 'lower level', 'category': 'parking', 'frequency': 27}, {'id': 160, 'term': 'bbq area', 'category': 'housing_features', 'frequency': 27}, {'id': 161, 'term': 'suite serves', 'category': 'parking', 'frequency': 27}, {'id': 162, 'term': 'bright airy', 'category': 'housing_layout', 'frequency': 27}, {'id': 163, 'term': 'media room', 'category': 'housing_layout', 'frequency': 27}, {'id': 164, 'term': 'centrally located', 'category': 'location', 'frequency': 27}, {'id': 165, 'term': 'first floor', 'category': 'flooring', 'frequency': 27}, {'id': 166, 'term': 'seamless living', 'category': 'housing_features', 'frequency': 27}, {'id': 167, 'term': 'kitchen featuring', 'category': 'kitchen', 'frequency': 27}, {'id': 168, 'term': 'wet bar', 'category': 'kitchen', 'frequency': 27}, {'id': 169, 'term': 'swimming pool', 'category': 'outdoor', 'frequency': 27}, {'id': 170, 'term': 'en suite', 'category': 'housing_layout', 'frequency': 27}, {'id': 171, 'term': 'kitchen equipped', 'category': 'kitchen', 'frequency': 27}, {'id': 172, 'term': 'bedrooms including', 'category': 'housing_layout', 'frequency': 27}, {'id': 173, 'term': 'primary suite serves', 'category': 'parking', 'frequency': 27}, {'id': 174, 'term': 'shopping dining parks', 'category': 'location', 'frequency': 27}, {'id': 175, 'term': 'kitchen dining', 'category': 'kitchen', 'frequency': 26}, {'id': 176, 'term': 'suite features', 'category': 'housing_layout', 'frequency': 26}, {'id': 177, 'term': 'fully remodeled', 'category': 'housing_features', 'frequency': 26}, {'id': 178, 'term': 'suite includes', 'category': 'housing_layout', 'frequency': 26}, {'id': 179, 'term': 'sliding glass doors', 'category': 'housing_features', 'frequency': 26}, {'id': 180, 'term': 'designed everyday living', 'category': 'parking', 'frequency': 26}, {'id': 181, 'term': 'vinyl plank flooring', 'category': 'flooring', 'frequency': 26}, {'id': 182, 'term': 'mature trees', 'category': 'outdoor', 'frequency': 25}, {'id': 183, 'term': 'close shopping', 'category': 'location', 'frequency': 25}, {'id': 184, 'term': 'bed bath', 'category': 'housing_layout', 'frequency': 25}, {'id': 185, 'term': 'located heart', 'category': 'location', 'frequency': 25}, {'id': 186, 'term': 'every detail', 'category': 'parking', 'frequency': 25}, {'id': 187, 'term': 'new construction', 'category': 'housing_features', 'frequency': 25}, {'id': 188, 'term': 'perfect everyday', 'category': 'parking', 'frequency': 25}, {'id': 189, 'term': 'dedicated laundry', 'category': 'housing_features', 'frequency': 25}, {'id': 190, 'term': 'spacious backyard', 'category': 'outdoor', 'frequency': 25}, {'id': 191, 'term': 'assigned parking', 'category': 'housing_features', 'frequency': 25}, {'id': 192, 'term': 'floor plan features', 'category': 'flooring', 'frequency': 25}, {'id': 193, 'term': 'primary suite features', 'category': 'housing_layout', 'frequency': 25}, {'id': 194, 'term': 'located desirable', 'category': 'location', 'frequency': 24}, {'id': 195, 'term': 'peaceful retreat', 'category': 'housing_features', 'frequency': 24}, {'id': 196, 'term': 'level features', 'category': 'parking', 'frequency': 24}, {'id': 197, 'term': 'everyday comfort', 'category': 'parking', 'frequency': 24}, {'id': 198, 'term': 'rv parking', 'category': 'parking', 'frequency': 24}, {'id': 199, 'term': 'ideal everyday', 'category': 'parking', 'frequency': 24}, {'id': 200, 'term': 'downstairs bedroom', 'category': 'housing_layout', 'frequency': 24}]

In [519]:
class EntityExtractor: 
    def __init__(self):
        with open("../data/processed/taxonomy.json", "r") as f:
            taxonomy = json.load(f)
        self.taxonomy = taxonomy['terms']
    def extract_bedrooms(self, text): 
        patterns = [ 
        r'(\d+)\s*(?:bed|beds|br|bd|bdrm|bdrms|bedroom|bedrooms)\b'
        ] 
        for pattern in patterns: 
            match = re.search(pattern, text, re.I) 
            if match: 
                return int(match.group(1)) 
        return None 
    def extract_price(self, text): 
        # Assumes cleaned text from Week 2 
        match = re.search(r'\$?(\d{5,})', text) 
        return int(match.group(1)) if match else None 
    def extract_bathrooms(self, text):
        patterns =  [
            r'(\d+\.?\d*)\s*(?:bath|baths|bathroom|bathrooms|ba)\b'
        ]
        for pattern in patterns: 
            match = re.search(pattern, text, re.I) 
            if match: 
                return int(match.group(1)) 
        return None 
    def extract_sqft(self, text): 
        patterns = [
            r"\b(sq\.?\s*ft\.?|sqft|sf|square feet)\b"
        ]
        for pattern in patterns:
            match = re.search(pattern, text, re.I)
            if match:
                cleaned_value = match.group(1).replace(",", "") # remove commas
                return int(match.group(1)) 
        return None 
    def extract_amenities(self, text):
        amenities = []
        text = text.lower()
        for item in self.taxonomy:
            term = item["term"].lower()
            if term in text:
                amenities.append({
                    "term": item["term"],
                    "category": item["category"]
                })
        return amenities
    def extract_all(self, text): 
        return { 
        'bedrooms': self.extract_bedrooms(text), 
        'bathrooms': self.extract_bathrooms(text), 
        'price': self.extract_price(text), 
        'sqft': self.extract_sqft(text), 
        'amenities': self.extract_amenities(text) 
        }

Test cases

In [520]:
extractor = EntityExtractor()

In [521]:
df_cleaned = pd.read_csv("../data/processed/cleaned_listing_sample.csv")
df_cleaned.head()

,L_ListingID,L_Address,L_City,beds,baths,price,remarks,cleaned_remarks
0,1169503734,133 Crystal Street,Taft,3.0,2.0,235000,This unique property offers two homes on one l...,This unique property offers two homes on one l...
1,1154220129,15664 Kadota,Victorville,4.0,4.0,459000,Beautiful Two-Story Home in Victorville – Spac...,Beautiful Two-Story Home in Victorville - Spac...
2,1159921951,949 S Manhattan Place 203,Los Angeles,3.0,2.0,689000,Presenting this exquisite second-floor corner ...,Presenting this exquisite second-floor corner ...
3,1170333192,1872 Seascape Boulevard,Aptos,3.0,3.0,1195000,Thoughtfully renovated coastal retreat tucked ...,Thoughtfully renovated coastal retreat tucked ...
4,1152463169,2085 Westhampton Drive,Arroyo Grande,3.0,2.0,1050000,Welcome to 2085 Westhampton Drive in Arroyo Gr...,Welcome to 2085 Westhampton Drive in Arroyo Gr...

In [522]:
df_cleaned[['remarks']].head(1)

                                             remarks
0  This unique property offers two homes on one l...

Checking extracting amenities

In [523]:
remark = """
Beautiful 4 bedroom home with granite countertops,
luxury vinyl plank flooring, pool, and RV parking.
"""

In [524]:
print(extractor.extract_amenities(remark))

[{'term': 'granite countertops', 'category': 'kitchen'}, {'term': 'plank flooring', 'category': 'flooring'}, {'term': 'vinyl plank flooring', 'category': 'flooring'}, {'term': 'rv parking', 'category': 'parking'}]

Extracting all

In [525]:
df_cleaned.columns

Index(['L_ListingID', 'L_Address', 'L_City', 'beds', 'baths', 'price',
       'remarks', 'cleaned_remarks'],
      dtype='str')

In [526]:
sample_remark = df_cleaned['cleaned_remarks'].iloc[0]

In [527]:
sample_remark

'This unique property offers two homes on one lot, creating an exceptional opportunity for both owner-occupants and investors alike. The front home features 2 bedrooms and 1 bathroom, while the rear unit offers 1 bedroom and 1 bathroom. Ideal for extended family, rental income, or a live-in-one-rent-the-other setup. The owner currently lives in one unit, which makes it easier to occupy or rent it out!'

In [528]:
print(extractor.extract_all(sample_remark))

{'bedrooms': 2, 'bathrooms': 1, 'price': None, 'sqft': None, 'amenities': []}

With this sample, only the first mentions of the bedrooms and bathrooms were extracted. Looking at the remark, they expanded on what the rear unit consists of.

In [529]:
example_remark = '''
There are 2.5 beds and 3 bathrooms.
'''

In [530]:
print(extractor.extract_all(sample_remark))

{'bedrooms': 2, 'bathrooms': 1, 'price': None, 'sqft': None, 'amenities': []}

#### Labeled dataset: 200-300 remarks with entity spans

In [531]:
labeled_sample = df_cleaned.sample(n=250, random_state=422)

In [532]:
#labeled_sample.to_csv('../data/labeled_sample.csv', index=False)
print(len(labeled_sample))

250

In [533]:
labeled_sample_cleaned = labeled_sample.drop(columns=['L_Address', 'remarks', 'L_City', 'L_ListingID'])

In [534]:
labeled_sample_cleaned.head()

     beds  baths    price                                    cleaned_remarks
606   2.0    1.0   399977  This inviting 2-bedroom, 1-bath residence sits...
255   2.0    3.0   389000  Multi-level townhouse looking for a little lov...
258   4.0    4.0  2625000  Experience refined Central Coast living in thi...
301   3.0    4.0  3325000  Wine country estate set across 52 acres in the...
233   3.0    2.0   650000  Welcome to this beautifully upgraded Connect f...

sqft (ground truth)

In [535]:
labeled_sample_cleaned['sqft'] = None

In [536]:
sqft_rows = labeled_sample_cleaned[
    labeled_sample_cleaned["cleaned_remarks"].str.contains(
        r'\d[\d,]*(?:[±+]|\+/-)?\s*(?:square\s+feet|sq\s*ft|sqft|\bsf\b)',
        case=False,
        na=False,
        regex=True
    )
]
len(sqft_rows)

87

In [537]:
def sqft_context(text, window=35):
    if pd.isna(text):
        return None

    match = re.search(
        r'\d[\d,]*(?:[±+]|\+/-)?\s*(?:square\s+feet|sq\s*ft|sqft|\bsf\b)',
        text,
        flags=re.IGNORECASE
    )

    if not match:
        return None

    start = max(0, match.start() - window)
    end = min(len(text), match.end() + window)

    return text[start:end]

In [538]:
labeled_sample_cleaned["sqft_context"] = labeled_sample_cleaned["cleaned_remarks"].apply(sqft_context)

In [539]:
labeled_sample_cleaned[labeled_sample_cleaned["sqft_context"].notna()][["sqft_context"]]

                                          sqft_context
258  tral Coast living in this stunning 4,146 squar...
301  and expansive sunset horizons. The 3,869 squar...
944  nal versatility. Inside, more than 1,500 squar...
288  ring 5 bedrooms, 4.5 bathrooms and 3,606 squar...
229  nt single-family home spans nearly 3,300 squar...
..                                                 ...
123  lit air conditioner, approximately 1400 square...
528  s 3 beds and 3 baths in a generous 2,201 squar...
628  ersatile home offers approximately 1,940 squar...
19   , this 3-story contemporary offers 1,655 squar...
997   own private bathroom. With almost 2100 square...

[87 rows x 1 columns]

In [540]:
def sqft_phrase(text):
    if pd.isna(text):
        return None

    match = re.search(
        r'\d[\d,]*(?:[±+]|\+/-)?\s*(?:square\s+feet|sq\s*ft|sqft|\bsf\b)',
        text,
        flags=re.IGNORECASE
    )

    return match.group(0) if match else None

In [541]:
labeled_sample_cleaned["sqft_phrase"] = labeled_sample_cleaned["cleaned_remarks"].apply(sqft_phrase)

In [542]:
labeled_sample_cleaned['sqft_phrase'].notna().sum()

np.int64(87)

In [543]:
labeled_sample_cleaned["sqft_phrase"] = labeled_sample_cleaned["cleaned_remarks"].apply(sqft_phrase)
labeled_sample_cleaned["sqft_context"] = labeled_sample_cleaned["cleaned_remarks"].apply(sqft_context)
labeled_sample_cleaned["sqft"] = None

In [544]:
df_cleaned['cleaned_remarks'].loc[258]

'Experience refined Central Coast living in this stunning 4,146 square feet. Spanish Colonial estate, perfectly positioned on a private 3 acre parcel within the exclusive gates of Santa Ysabel Ranch. Enjoy sweeping 180° views of vineyards and mountains from nearly every room. This 4-bedroom, 3.5-bath home welcomes you through a grand rotunda entry with soaring ceilings, custom lighting, and travertine flooring throughout. The formal living and dining rooms feature tall Anderson windows framing breathtaking vistas and a cozy gas fireplace. The gourmet kitchen is equipped with GE Monogram stainless appliances, including a six-burner range, double ovens, wine fridge, and granite countertops with maple cabinetry. The adjoining family room and casual dining area create an inviting space for entertaining with seamless indoor-outdoor flow. The spacious primary suite offers privacy, dual walk-in closets, and a luxurious bath with soaking tub and large shower. Additional bedrooms and a flexible office space capture beautiful hillside and sunset views. Outdoor living shines with expansive flagstone patios, multiple sitting areas, and lush landscaping surrounded by heritage oaks - perfect for dining, relaxing, or entertaining under the stars. Additional features include an epoxy-finished 3-car garage with custom cabinetry, Culligan water system, American district telegraph security, and custom lighting throughout. Santa Ysabel Ranch offers 24/7 gated security, walking trails, tennis courts, and a serene lake setting - an unparalleled blend of luxury, privacy, and natural beauty.'

In [545]:
labeled_sample_cleaned.head(10)

,beds,baths,price,cleaned_remarks,sqft,sqft_context,sqft_phrase
606,2.0,1.0,399977,"This inviting 2-bedroom, 1-bath residence sits...",None,NaN,NaN
255,2.0,3.0,389000,Multi-level townhouse looking for a little lov...,None,NaN,NaN
258,4.0,4.0,2625000,Experience refined Central Coast living in thi...,None,"tral Coast living in this stunning 4,146 squar...","4,146 square feet"
301,3.0,4.0,3325000,Wine country estate set across 52 acres in the...,None,"and expansive sunset horizons. The 3,869 squar...","3,869 square feet"
233,3.0,2.0,650000,Welcome to this beautifully upgraded Connect f...,None,NaN,NaN
143,3.0,3.0,1460600,"Welcome to this spectacular 3-bedroom, 3-bath ...",None,NaN,NaN
378,4.0,3.0,950000,Welcome to 70900 Jasmine Lane located in beaut...,None,NaN,NaN
679,3.0,2.0,429000,"Welcome to this stunning, move-in-ready reside...",None,NaN,NaN
944,4.0,2.0,920000,"Welcome to 7039 Sylvia Avenue, a beautifully u...",None,"nal versatility. Inside, more than 1,500 squar...","1,500 square feet"
37,3.0,2.0,599900,GRAND TERRACE SINGLE-STORY-Welcome home to thi...,None,NaN,NaN

In [546]:
def label_sqft(phrase):
    if pd.isna(phrase):
        return None

    match = re.search(r'(\d[\d,]*)', phrase)

    if match:
        return int(match.group(1).replace(",", ""))

    return None

In [547]:
labeled_sample_cleaned["sqft"] = labeled_sample_cleaned["sqft_phrase"].apply(label_sqft)

In [548]:
labeled_sample_cleaned['sqft'].notna().sum()

np.int64(87)

In [549]:
labeled_sample_cleaned.columns

Index(['beds', 'baths', 'price', 'cleaned_remarks', 'sqft', 'sqft_context',
       'sqft_phrase'],
      dtype='str')

In [550]:
labeled_sample_cleaned['sqft_context'].notna().sum()

np.int64(87)

In [551]:
labeled_sample_cleaned['sqft_phrase'].notna().sum()

np.int64(87)

In [552]:
labeled_cleaned = labeled_sample_cleaned.drop(columns=['sqft_phrase', 'sqft_context'])

In [553]:
labeled_cleaned["sqft"] = labeled_cleaned["sqft"].fillna("None")

In [554]:
labeled_cleaned['sqft'].isna().sum()

np.int64(0)

Amendities (ground truth)

In [555]:
# Using taxonomy as a helper/resource
def suggest_amenities(text):
    suggestions = []

    for term in taxonomy_terms:
        if term.lower() in text.lower():
            suggestions.append(term)

    return suggestions

taxonomy_terms = sorted(
    [term["term"] for term in taxonomy["terms"]],
    key=len,
    reverse=True
)

In [556]:
labeled_cleaned["candidate_amenities"] = (
    labeled_cleaned["cleaned_remarks"]
    .apply(suggest_amenities)
)

In [557]:
labeled_cleaned['candidate_amenities']

606    [flooring throughout, sliding glass doors, mou...
255           [primary bedroom, dining room, car garage]
258    [spacious primary suite, primary suite offers,...
301    [primary suite serves, quartz countertops, pri...
233    [stainless steel appliances, conveniently loca...
                             ...
19     [primary suite offers, quartz countertops, pan...
449    [effortless entertaining, fitness center, prim...
755    [flooring throughout, quartz countertops, rece...
148    [laminate flooring, covered patio, living room...
997    [primary bedroom, full bathrooms, indoor laund...
Name: candidate_amenities, Length: 250, dtype: object

Go through the suggested amenities

In [558]:
#labeled_cleaned.to_csv("../data/labeled_cleaned.csv")

Keep in mind: The amentities are meant to represent the features that the property offers, not surrounding words or phrases that happen to contain those features. I will also avoid any marketing phrases. An amenity will represent a tangible property feature, space, service, or location advantage that the property provides. So, if there are any phrases that are not supportive of this, they will be removed (to keep ground truth)

In [559]:
all_amenities = [
    amenity
    for row in labeled_cleaned["candidate_amenities"]
    for amenity in row
]

amenity_counts = Counter(all_amenities)

amenity_counts.most_common()

[('living space', 86),
 ('primary suite', 72),
 ('car garage', 67),
 ('natural light', 63),
 ('floor plan', 63),
 ('living room', 52),
 ('everyday living', 44),
 ('conveniently located', 41),
 ('located near', 39),
 ('full bath', 38),
 ('recessed lighting', 35),
 ('easy access', 33),
 ('stainless steel', 30),
 ('living spaces', 30),
 ('conveniently located near', 28),
 ('home office', 27),
 ('spacious living', 27),
 ('full bathroom', 27),
 ('family room', 25),
 ('quartz countertops', 25),
 ('stainless steel appliances', 25),
 ('outdoor space', 24),
 ('suite offers', 24),
 ('bath home', 24),
 ('dining room', 23),
 ('fully remodeled', 23),
 ('laundry room', 22),
 ('primary suite offers', 21),
 ('covered patio', 20),
 ('granite countertops', 20),
 ('updated kitchen', 20),
 ('open floor', 20),
 ('ideally located', 20),
 ('abundant natural light', 19),
 ('vaulted ceilings', 19),
 ('direct access', 19),
 ('mountain views', 18),
 ('primary bedroom', 18),
 ('open floor plan', 18),
 ('golf course', 18),
 ('gated community', 18),
 ('spacious primary', 17),
 ('plank flooring', 17),
 ('freeway access', 17),
 ('flooring throughout', 16),
 ('fitness center', 16),
 ('flows seamlessly', 16),
 ('wood flooring', 15),
 ('private balcony', 15),
 ('beautifully remodeled', 15),
 ('main level', 15),
 ('gourmet kitchen', 14),
 ('sparkling pool', 14),
 ('parking space', 14),
 ('spacious primary suite', 13),
 ('fire pit', 13),
 ('vinyl plank flooring', 13),
 ('kitchen features', 13),
 ('center island', 13),
 ('private patio', 13),
 ('convenient access', 13),
 ('everyday convenience', 12),
 ('swimming pool', 12),
 ('remodeled kitchen', 12),
 ('added privacy', 12),
 ('located within', 12),
 ('breakfast bar', 12),
 ('hardwood floors', 12),
 ('panoramic views', 12),
 ('located near shopping', 12),
 ('near shopping', 12),
 ('sliding glass', 11),
 ('additional bedrooms', 11),
 ('gas fireplace', 11),
 ('laminate flooring', 11),
 ('mature landscaping', 11),
 ('full bathrooms', 11),
 ('laundry area', 11),
 ('tennis courts', 10),
 ('new roof', 10),
 ('assigned parking', 10),
 ('fruit trees', 10),
 ('cozy fireplace', 10),
 ('solar panels', 10),
 ('three bedrooms', 10),
 ('spacious living room', 10),
 ('primary suite serves', 9),
 ('suite serves', 9),
 ('private backyard', 9),
 ('effortless entertaining', 9),
 ('centrally located', 9),
 ('brand new', 9),
 ('high ceilings', 9),
 ('ample space', 9),
 ('prime location', 9),
 ('secondary bedrooms', 9),
 ('enjoy access', 9),
 ('counter space', 9),
 ('home located', 9),
 ('sized bedrooms', 8),
 ('ideally located near', 8),
 ('comfortable living space', 8),
 ('indoor laundry', 8),
 ('second bedroom', 7),
 ('tile flooring', 7),
 ('glass doors', 7),
 ('upper level', 7),
 ('outdoor kitchen', 7),
 ('large center island', 7),
 ('mature trees', 7),
 ('seamless flow', 7),
 ('hardwood flooring', 7),
 ('spacious bedrooms', 7),
 ('kitchen featuring', 7),
 ('generously sized bedrooms', 6),
 ('shopping centers', 6),
 ('parking spaces', 6),
 ('tankless water heater', 6),
 ('attached garage', 6),
 ('tankless water', 6),
 ('formal dining room', 6),
 ('spacious backyard', 6),
 ('every detail', 6),
 ('kitchen showcases', 6),
 ('dedicated laundry', 6),
 ('ocean views', 6),
 ('two additional bedrooms', 6),
 ('lower level', 6),
 ('sliding glass doors', 5),
 ('endless possibilities', 5),
 ('peaceful retreat', 5),
 ('suite includes', 5),
 ('dual sinks', 5),
 ('en suite', 5),
 ('two bedrooms', 5),
 ('community pool', 5),
 ('wet bar', 5),
 ('downstairs bedroom', 5),
 ('first floor', 5),
 ('primary suite features', 4),
 ('suite features', 4),
 ('everyday comfort', 4),
 ('spacious home', 3),
 ('media room', 3),
 ('detached garage', 3),
 ('floor plan features', 3),
 ('bright open', 2),
 ('level features', 2),
 ('patio perfect', 2),
 ('seamless living', 2),
 ('features spacious', 1),
 ('new construction', 1),
 ('kitchen equipped', 1)]

In [560]:
len(amenity_counts)

153

In [561]:
removed_amenities= [
 'everyday living', 'conveniently located', 'located near', 
 'easy access', 'conveniently located near', 'ideally located', 
 'spacious primary', 'flooring throughout', 'fully remodeled', 
 'primary suite offers', 'suite offers', 'direct access', 'flows seamlessly', 
 'convenient access', 'everyday convenience', 'located within', 
 'prime location', 'brand new', 'ample space', 'home located', 
 'beautifully remodeled', 'ideally located near', 'comfortable living space', 
 'enjoy access', 'endless possibilities', 'seamless flow', 'effortless entertaining', 
 'primary suite serves', 'suite serves', 'kitchen showcases', 'everyday comfort', 
 'every detail', 'primary suite features', 'suite features','suite includes', 
 'floor plan features', 'peaceful retreat', 'kitchen featuring', 'level features', 
 'spacious home', 'bright open', 'patio perfect', 'kitchen equipped',
 'features spacious','bedrooms including', 'seamless living', 'located minutes',
 'feet living space', 'space home'
]

In [562]:
labeled_cleaned["candidate_amenities"] = labeled_cleaned["candidate_amenities"].apply(
    lambda amenities: [
        x for x in amenities
        if x not in removed_amenities
    ]
)

In [563]:
all_amenities = [
    amenity
    for row in labeled_cleaned["candidate_amenities"]
    for amenity in row
]

amenity_counts = Counter(all_amenities)

amenity_counts.most_common()

[('living space', 86),
 ('primary suite', 72),
 ('car garage', 67),
 ('natural light', 63),
 ('floor plan', 63),
 ('living room', 52),
 ('full bath', 38),
 ('recessed lighting', 35),
 ('stainless steel', 30),
 ('living spaces', 30),
 ('home office', 27),
 ('spacious living', 27),
 ('full bathroom', 27),
 ('family room', 25),
 ('quartz countertops', 25),
 ('stainless steel appliances', 25),
 ('outdoor space', 24),
 ('bath home', 24),
 ('dining room', 23),
 ('laundry room', 22),
 ('covered patio', 20),
 ('granite countertops', 20),
 ('updated kitchen', 20),
 ('open floor', 20),
 ('abundant natural light', 19),
 ('vaulted ceilings', 19),
 ('mountain views', 18),
 ('primary bedroom', 18),
 ('open floor plan', 18),
 ('golf course', 18),
 ('gated community', 18),
 ('plank flooring', 17),
 ('freeway access', 17),
 ('fitness center', 16),
 ('wood flooring', 15),
 ('private balcony', 15),
 ('main level', 15),
 ('gourmet kitchen', 14),
 ('sparkling pool', 14),
 ('parking space', 14),
 ('spacious primary suite', 13),
 ('fire pit', 13),
 ('vinyl plank flooring', 13),
 ('kitchen features', 13),
 ('center island', 13),
 ('private patio', 13),
 ('swimming pool', 12),
 ('remodeled kitchen', 12),
 ('added privacy', 12),
 ('breakfast bar', 12),
 ('hardwood floors', 12),
 ('panoramic views', 12),
 ('located near shopping', 12),
 ('near shopping', 12),
 ('sliding glass', 11),
 ('additional bedrooms', 11),
 ('gas fireplace', 11),
 ('laminate flooring', 11),
 ('mature landscaping', 11),
 ('full bathrooms', 11),
 ('laundry area', 11),
 ('tennis courts', 10),
 ('new roof', 10),
 ('assigned parking', 10),
 ('fruit trees', 10),
 ('cozy fireplace', 10),
 ('solar panels', 10),
 ('three bedrooms', 10),
 ('spacious living room', 10),
 ('private backyard', 9),
 ('centrally located', 9),
 ('high ceilings', 9),
 ('secondary bedrooms', 9),
 ('counter space', 9),
 ('sized bedrooms', 8),
 ('indoor laundry', 8),
 ('second bedroom', 7),
 ('tile flooring', 7),
 ('glass doors', 7),
 ('upper level', 7),
 ('outdoor kitchen', 7),
 ('large center island', 7),
 ('mature trees', 7),
 ('hardwood flooring', 7),
 ('spacious bedrooms', 7),
 ('generously sized bedrooms', 6),
 ('shopping centers', 6),
 ('parking spaces', 6),
 ('tankless water heater', 6),
 ('attached garage', 6),
 ('tankless water', 6),
 ('formal dining room', 6),
 ('spacious backyard', 6),
 ('dedicated laundry', 6),
 ('ocean views', 6),
 ('two additional bedrooms', 6),
 ('lower level', 6),
 ('sliding glass doors', 5),
 ('dual sinks', 5),
 ('en suite', 5),
 ('two bedrooms', 5),
 ('community pool', 5),
 ('wet bar', 5),
 ('downstairs bedroom', 5),
 ('first floor', 5),
 ('media room', 3),
 ('detached garage', 3),
 ('new construction', 1)]

In [564]:
len(amenity_counts)

108

In [567]:
labeled_cleaned = labeled_cleaned.rename(columns={'candidate_amenities': 'amenities'})

In [568]:
labeled_cleaned.head()

,beds,baths,price,cleaned_remarks,sqft,amenities
606,2.0,1.0,399977,"This inviting 2-bedroom, 1-bath residence sits...",None,"[sliding glass doors, mountain views, second b..."
255,2.0,3.0,389000,Multi-level townhouse looking for a little lov...,None,"[primary bedroom, dining room, car garage]"
258,4.0,4.0,2625000,Experience refined Central Coast living in thi...,4146.0,"[spacious primary suite, granite countertops, ..."
301,3.0,4.0,3325000,Wine country estate set across 52 acres in the...,3869.0,"[quartz countertops, primary suite]"
233,3.0,2.0,650000,Welcome to this beautifully upgraded Connect f...,None,"[stainless steel appliances, quartz countertop..."

Using the extractor class

In [569]:
labeled_extract = labeled_cleaned.copy()

In [570]:
labeled_extract = labeled_extract.drop(columns=['beds', 'baths', 'price', 'sqft', 'amenities'])

In [572]:
labeled_extract.head()

                                       cleaned_remarks
606  This inviting 2-bedroom, 1-bath residence sits...
255  Multi-level townhouse looking for a little lov...
258  Experience refined Central Coast living in thi...
301  Wine country estate set across 52 acres in the...
233  Welcome to this beautifully upgraded Connect f...

In [573]:
labeled_extract.shape

(250, 1)

In [578]:
labeled_extract['extracted_bd'] = labeled_extract['cleaned_remarks'].apply(
    extractor.extract_bedrooms
)

In [579]:
labeled_extract['extracted_bd'].isna().sum()

np.int64(166)

In [581]:
labeled_extract['extracted_br'] = labeled_extract['cleaned_remarks'].apply(
    extractor.extract_bathrooms
)

ValueError: invalid literal for int() with base 10: '4.5'

In [582]:
labeled_extract['extracted_price'] = labeled_extract['cleaned_remarks'].apply(
    extractor.extract_price
)

In [586]:
labeled_extract['extracted_price'].isna().sum()

np.int64(234)

In [583]:
labeled_extract['extracted_sqft'] = labeled_extract['cleaned_remarks'].apply(
    extractor.extract_sqft
)

ValueError: invalid literal for int() with base 10: 'square feet'

In [584]:
labeled_extract['extracted_amenities'] = labeled_extract['cleaned_remarks'].apply(
    extractor.extract_amenities
)

In [585]:
labeled_extract['extracted_amenities'].isna().sum()

np.int64(0)